#
# GNUmakefile for target NSTableView_test
# begin - generated by buildtool
#

include $(GNUSTEP_MAKEFILES)/common.make

APP_NAME = NSTableView_test

NSTableView_test_OBJC_FILES = NSTableView_test/main.m \
	NSTableView_test/AppDelegate.m 

NSTableView_test_C_FILES = 

NSTableView_test_CPP_FILES = 

NSTableView_test_OBJCPP_FILES = 

NSTableView_test_RESOURCE_FILES = NSTableView_test/Assets.xcassets \
	NSTableView_test/Base.lproj/MainMenu.xib \
	NSTableView_testInfo.plist 

ADDITIONAL_INCLUDE_DIRS += -I. \
	-I./NSTableView_test 

ADDITIONAL_OBJC_LIBS += 

include $(GNUSTEP_MAKEFILES)/common.make
include $(GNUSTEP_MAKEFILES)/application.make

#
# end - generated makefile
#
